sudo: false
language: node_js
node_js:
  - v6
  - v5
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g gulp-cli
script: gulp test
